version: '3.7'

services:

  web:
    build: .
    ports:
      - 80:80
    volumes:
      - ./html:/var/www/html
  db:
      image: mysql
      volumes:
        - ./db_data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: docker_database
      ports:
        - 3306:3306
  
